plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://thingking-machine.github.io
baseurl: /fireworksr

title: Thingking Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Thingking-Machine
  verb: Thingking
  instructions_file: thingking.md
  token: fireworks
  server: https://localhost:443
  apiUrl: https://api.fireworks.ai/inference/v1/chat/completions

app:
  worker_name: fireapi.js

lm:
  model: glm-5p2
  max_tokens: 4096
  reasoning_effort: high
  prompt_truncate_len: 10000
  temperature: 1.0
  top_p: 0.7
  top_k: 50

github_settings:
  owner: thingking-machine
  repo: thingking_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
